slurmstepd-gpu-compute: error: *** JOB 2096 ON gpu-compute CANCELLED AT 2022-09-06T11:23:28 ***
Traceback (most recent call last):
  File "/mnt/nas/users/mjm/GitHub/private_conti_test/Python_implm/simulation_runs/indep/tradeoffs/sinusoidal/indep_sinusoidal_try_1.py", line 46, in <module>
  File "/mnt/nas/users/mjm/.conda/envs/mjm_env_gpu/lib/python3.8/site-packages/pandas/core/generic.py", line 3551, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/mnt/nas/users/mjm/.conda/envs/mjm_env_gpu/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1180, in to_csv
    csv_formatter.save()
  File "/mnt/nas/users/mjm/.conda/envs/mjm_env_gpu/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 241, in save
    with get_handle(
  File "/mnt/nas/users/mjm/.conda/envs/mjm_env_gpu/lib/python3.8/site-packages/pandas/io/common.py", line 697, in get_handle
    check_parent_directory(str(handle))
  File "/mnt/nas/users/mjm/.conda/envs/mjm_env_gpu/lib/python3.8/site-packages/pandas/io/common.py", line 571, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/mnt/nas/users/mjm/GitHub/private_conti_test/Python_implm/simulation_runs/indep/tradeoffs/sinusoidal'
